from aiogram.utils.callback_data import CallbackData

navigation = CallbackData('nav', 'to', 'payload')
courier = CallbackData('courier', 'order_id', 'payload')
withdrawal_history = CallbackData('withdrawal_history', 'stat_id')
statistic = CallbackData('statistic', 'action', 'payload')
referral_list = CallbackData('referral_list', 'to', 'ref_id', 'original_ref_id', 'page')
referral_withdrawal = CallbackData('ref_withdraw', 'type')
bank_choose = CallbackData('bank_choose', 'bank', 'type', 'payload')
token_choose = CallbackData('token_choose', 'token', 'payload')
active_couriers = CallbackData('active_couriers', 'to', 'telegram_id', 'page')
year_choose = CallbackData('year', 'value', 'action')
crm_notify = CallbackData('crm_notify', 'deal_id', 'payload')
week_choose = CallbackData('week', 'year', 'value', 'action')
day_choose = CallbackData('day', 'date')
order_choose = CallbackData('order', 'id')
order_update = CallbackData('order_upd', 'type', 'id')
exchange = CallbackData('exchange', 'ex_type', 'deal_type')
operator_choose = CallbackData('operator', 'id', 'action')
operator_update = CallbackData('operator_upd', 'id', 'action')
referral_level_choose = CallbackData('ref_lev_choose', 'level', 'action')
referral_choose = CallbackData('ref_choose', 'id', 'action')
referral_update = CallbackData('ref_upd', 'id')
admin_stat = CallbackData('admin_stat', 'orig_id', 'start_day')
client_change = CallbackData('client_change', 'to', 'order_id', 'input_currency')
operator_order = CallbackData('oper_order', 'order_id', 'action')
customer_order = CallbackData('cust_order', 'order_id', 'action')
courier_order = CallbackData('cour_order', 'order_id')
courier_choose = CallbackData('courier_choose', 'order_id', 'telegram_id')

movers = CallbackData('movers', 'to', 'payload')
movers_orig_ref_choose = CallbackData('movers_orig_ref_choose', 'id', 'page')
movers_order = CallbackData('movers_order', 'order_id', 'action')
movers_update = CallbackData('movers_update', 'action', 'id')
